// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sancmhdtvbgpszkbobnm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNhbmNtaGR0dmJncHN6a2JvYm5tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3MjMzNTQsImV4cCI6MjA2NTI5OTM1NH0.An6gAdzWh1YwaX0V6IvxLtjlx1r2UOzfhYZ8P9rKLRg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);